version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "5000:5000"
        environment:
            - ROSBRIDGE_SERVER_IP=${ROSBRIDGE_SERVER_IP}
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"